name: Upload Assets

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'

      - uses: calcit-lang/setup-cr@0.0.3
        with:
          version: "0.9.0-a1"

      - name: "compiles calcit to js"
        run: >
          caps --ci && cr --once js

      - run: yarn && yarn vite build --base=./
        name: Build web assets

      - name: Deploy to server
        id: deploy
        uses: Pendect/action-rsyncer@v2.0.0
        env:
          DEPLOY_KEY: ${{secrets.rsync_private_key}}
        with:
          flags: "-avzr --progress"
          options: ""
          ssh_options: ""
          src: "dist/*"
          dest: "rsync-user@tiye.me:/web-assets/repo/${{ github.repository }}"

      - name: Display status from deploy
        run: echo "${{ steps.deploy.outputs.status }}"
